### PR TITLE
KEEP-ALIVE-STREAM: return stream when hit eof when using read-sequence as well as read-byte

### PR DESCRIPTION
**Pull request by ajberkley**

### CODE REVIEW

**Comment by ajberkley** [comment]
The name for the function I pulled out is pretty bogus.  Will fix and clean-up the logic a bit so it isn't so... convoluted.

**Comment by ajberkley** [comment]
OK, I cleaned up the mess somewhat.  We also weren't handling the keep-alive nil case for fetch properly --- so I added an explicit close in fetch.  It doesn't hurt to do it twice --- it's a no op.

**Comment by Linden6** [comment]
With regards to the end of dex:fetch in dexador.lisp:
```
...
(let ((body (apply #'dex:get uri :want-stream t :force-binary t
                   (remove-from-plist args :if-exists))))
  (alexandria:copy-stream body out)
  ;; Nominally the body gets closed, but if keep-alive is nil we need to explicitly do it,
  ;; and it doesn't hurt to do it twice.
  (close body)))))
```

If the stream is already closed then trying to close it again raises the following error:
  The value NIL is not of type STREAM.

The last line of dex:fetch, therefore, needs to check if the stream is still open before closing it, and so perhaps should be:
```
...
(let ((body (apply #'dex:get uri :want-stream t :force-binary t
                   (remove-from-plist args :if-exists))))
  (alexandria:copy-stream body out)
  ;; Nominally the body gets closed, but if keep-alive is nil we need to explicitly do it,
  ;; and it doesn't hurt to do it twice.
  (when (open-stream-p body)
    (close body))))))
```

**Comment by ajberkley** [comment]
I can't reproduce that... can you give me a hint for what to do?

**Comment by ajberkley** [comment]
Oh, I seem to be out of sync with this pr :(  will push the fix.

**Comment by ajberkley** [comment]
Argh, no I'm not.  Can you give me a hint to reproduce?

**Comment by Linden6** [comment]
I'm sorry.  This error isn't occurring any more, so I think it was just something wrong at my end - but as I can't reproduce it I don't know what.  Therefore, please just ignore this issue.

(In the unlikely event that it does reoccur I'll put together a short script so that you can reproduce it.  Thanks.)

**Comment by Linden6** [comment]
No error with:
```
(require :dexador)
(dex:fetch "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Queen_Elizabeth_II_in_March_2015.jpg/220px-Queen_Elizabeth_II_in_March_2015.jpg" "/tmp/queen.jpg" :use-connection-pool nil :keep-alive nil)
```

But with:
```
(require :dexador)
(dex:fetch "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Queen_Elizabeth_II_in_March_2015.jpg/220px-Queen_Elizabeth_II_in_March_2015.jpg" "/tmp/queen.jpg")
```

I get:
_debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1001834103}>:
  The value
    NIL
  is not of type
    STREAM_

If I change the end of dex:fetch from:
`(close body)`
to:
```
(when (open-stream-p body)
  (close body))
```

Then no errors arise.

**Comment by ajberkley** [comment]
OK, I can't reproduce but it's a perfectly reasonable thing to wrap the close with when open-stream-p.  It does point at a bug in the keep-alive stuff somewhere maybe.

**Comment by Linden6** [comment]
Thanks.  Yes, it would seem that somewhere in the keep-alive stuff (which is beyond my immediate comprehension) the stream is perhaps deleted rather than simply closed.

**Pull request merged**
