### PR TITLE
Delete the bundled certificates.

### PR DESCRIPTION
**Pull request by fukamachi**
It used to be mainly for Windows, which doesn't have any in its terminal environment, but it's not so useful now that it has a WinHTTP backend.

### CODE REVIEW

**Comment by anranyicheng** [comment]
Hi，
why delete the certificate? If it is deleted, the user must specify the certificate when using the function?

**Comment by fukamachi** [comment]
If it doesn't exist, cl+ssl should pick the default certificates installed in the OS.
https://github.com/fukamachi/dexador/blob/012dd43f127bae3ef0bbe4a4e04cbfc9752e4e1f/src/backend/usocket.lisp#L375

Users have to manage (update) it themselves, but it may be better than continuing to use the old bundled one.

**Comment by fukamachi** [comment]
I just fixed it to check if `*ca-bundle*` is set.

**Comment by anranyicheng** [comment]
Yeah, well done patch.

Eitaro Fukamachi ***@***.***> 于2024年7月11日周四 16:31写道：

**Pull request merged**
